server:
  port: 8099

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: CONTACT-SERVICE
          uri: lb://CONTACT-SERVICE
          predicates:
            - Path=/contact/**
          filters:
            - name: CircuitBreaker
              args:
                name: CONTACT-SERVICE
                fallbackuri: forward:/contactServiceFallBack


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream